# Generated by Django 3.2.9 on 2021-11-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
