# Generated by Django 3.2.9 on 2021-11-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_listing_watchers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bid',
            new_name='offer',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='title',
        ),
        migrations.AddField(
            model_name='bid',
            name='dateTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
