# Generated by Django 3.2.9 on 2021-11-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20211120_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='initialBid',
            field=models.FloatField(default=0),
        ),
    ]
