# Generated by Django 3.2.9 on 2021-11-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20211120_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='user',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='comment',
            name='listingID',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.CharField(max_length=64),
        ),
    ]
