# Generated by Django 3.2.9 on 2021-11-20 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_alter_bid_listingid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='listingID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auctions.listing'),
        ),
    ]
